USE [master];
GO

/*SE VALIDA SI EXISTA LA BASE DE DATOS ANTES DE CREARLA*/
IF EXISTS(SELECT 1 FROM SYS.databases WHERE NAME = 'ProyectoII') 
	DROP DATABASE [ProyectoII]
GO
CREATE DATABASE ProyectoII;
GO

/*NOS UBICAMOS EN LA BASE DATOS LUEGO DE CREADA*/
USE [ProyectoII];
GO

/*SE VALIDA SI EXISTA EL ESQUEMA ANTES DE CREARLO*/
IF EXISTS(SELECT 1 FROM SYS.schemas WHERE NAME = 'Proyecto2') 
	DROP SCHEMA Proyecto2;
GO
CREATE SCHEMA [Proyecto2]; 
GO

BEGIN TRAN

	/*CREACIÓN DE TABLAS*/

	IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'GEO_PAIS' AND type ='U') 
		DROP TABLE Proyecto2.GEO_PAIS

	CREATE TABLE Proyecto2.GEO_PAIS ( 
		COD_PAIS INTEGER not null, 
		NOMBRE_PAIS VARCHAR(100),
		CONSTRAINT GEP_PAIS_PK PRIMARY KEY ( COD_PAIS)
	);

	IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'GEO_PROVINCIA' AND type ='U') 
		DROP TABLE Proyecto2.GEO_PROVINCIA

	CREATE TABLE Proyecto2.GEO_PROVINCIA ( 
		COD_PAIS INTEGER not null, 
		COD_PROVINCIA INTEGER not null, 
		NOMBRE_PRO VARCHAR(100),
		CONSTRAINT GEO_PRO_PK PRIMARY KEY ( COD_PAIS, COD_PROVINCIA ),
		CONSTRAINT GEO_PRO_FK1 FOREIGN KEY (COD_PAIS) REFERENCES Proyecto2.GEO_PAIS ( COD_PAIS )
	);

	IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'GEO_CANTON' AND type ='U') 
		DROP TABLE Proyecto2.GEO_CANTON

	CREATE TABLE Proyecto2.GEO_CANTON ( 
		COD_PAIS INTEGER not null, 
		COD_PROVINCIA INTEGER not null, 
		COD_CANTON INTEGER not null, 
		NOMBRE_CAN VARCHAR(100),
		CONSTRAINT GEO_CAN_PK PRIMARY KEY ( COD_PAIS, COD_PROVINCIA, COD_CANTON ),
		CONSTRAINT GEO_CAN_FK1 FOREIGN KEY (COD_PAIS, COD_PROVINCIA) REFERENCES Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA )
	);

	IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'GEO_DISTRITO' AND type ='U') 
		DROP TABLE Proyecto2.GEO_DISTRITO

	CREATE TABLE Proyecto2.GEO_DISTRITO ( 
		COD_PAIS INTEGER not null, 
		COD_PROVINCIA INTEGER not null, 
		COD_CANTON INTEGER not null, 
		COD_DISTRITO INTEGER not null, 
		NOMBRE_DIST VARCHAR(100), 
		AREA DECIMAL(18,2),
		CONSTRAINT GEO_DIST_PK PRIMARY KEY ( COD_PAIS, COD_PROVINCIA, COD_CANTON, COD_DISTRITO ),
		CONSTRAINT GEO_DIST_FK1 FOREIGN KEY (COD_PAIS, COD_PROVINCIA, COD_CANTON) REFERENCES Proyecto2.GEO_CANTON ( COD_PAIS, COD_PROVINCIA , COD_CANTON)
	);

	/*INSERT DE DATOS EN TABLAS PAÍS Y PROVINCIA*/

	INSERT INTO Proyecto2.GEO_PAIS ( COD_PAIS, NOMBRE_PAIS ) VALUES ( 1, 'COSTA RICA');
	INSERT INTO Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA, NOMBRE_PRO ) VALUES (1,1,'San Jose');
	INSERT INTO Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA, NOMBRE_PRO ) VALUES (1,2,'Alajuela');
	INSERT INTO Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA, NOMBRE_PRO ) VALUES (1,3,'Cartago');
	INSERT INTO Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA, NOMBRE_PRO ) VALUES (1,4,'Heredia');
	INSERT INTO Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA, NOMBRE_PRO ) VALUES (1,5,'Guanacaste');
	INSERT INTO Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA, NOMBRE_PRO ) VALUES (1,6,'Puntarenas');
	INSERT INTO Proyecto2.GEO_PROVINCIA ( COD_PAIS, COD_PROVINCIA, NOMBRE_PRO ) VALUES (1,7,'Limon');

COMMIT TRAN;